exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - script
  - src

remote_theme: marella/jekyll-theme-documentation

permalink: pretty

nav:
  - Getting Started :
    - Introduction: ''
  - 資産運用:
    - 資産運用: doc/investment/conclusion
    - 決算: doc/investment/account
    - 早期退職: doc/investment/fire
